version: '3'
services:
  example:
    build: .
    ports:
      - "8080:8080"
  example-remote-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    cap_add:
      - SYS_PTRACE
    ports:
      - "8081:8080"
      - "40000:40000"